### ISSUE TITLE
open-websockets metric returns negative value

### ISSUE THREAD

**Issue by leolux** [vert-x3/vertx-dropwizard-metrics#10]
```
"vertx.http.servers.0.0.0.0:80.open-websockets": {
     "count": -3
 }
```
Version: 3.1.0-SNAPSHOT

**Comment by vietj** [comment]
hi, can you provide a small chunk of code that reproduce this problem ?

**Comment by leolux** [comment]
https://github.com/leolux/vertx_reprod_negative_metric

**Comment by leolux** [comment]
Any problems?

**Comment by vietj** [comment]
no, I need to look at it :-)

**Comment by vietj** [comment]
founds the issue, it's due to the websocket upgrade that is not properly handled by the Vert.x Metrics SPI in vertx core. I'll fix that soon, it should not be much difficult.

**Comment by vietj** [comment]
so I nailed down the issue in core, this should be fixes soon, I'll let you know and you can try it again at this moment.

**Comment by leolux** [comment]
Thanks!

**Comment by vietj** [comment]
Hi, the bug fix has been merged in vertx-core, would you mind to check with Vert.x 3.1.0-SNAPSHOT ? you can consumer them from Sonatype OSS SNAPSHOT repository https://oss.sonatype.org/content/repositories/snapshots/

**Comment by leolux** [comment]
Currently I have a compile error: 
```Description	Resource	Path	Location	Type
The type HttpServerMetricsImpl must implement the inherited abstract method HttpServerMetrics<RequestMetric,WebSocketMetric,Timer.Context>.upgrade(RequestMetric, ServerWebSocket)	HttpServerMetricsImpl.java	/vertx-dropwizard-metrics/src/main/java/io/vertx/ext/dropwizard/impl	line 32	Java Problem
```

**Comment by vietj** [comment]
right, I forgot to push changes :-) now it should be good

**Comment by leolux** [comment]
It works! Thank you vietj!
