### ISSUE TITLE
Metrics name defined in client options is ignored

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-dropwizard-metrics#106]
This implementation of the SPI seem to ignore the [metrics name defined in client options](https://github.com/eclipse-vertx/vert.x/blob/fa128df3d747b726da3113ebd8638773d68a9d32/src/main/java/io/vertx/core/net/ClientOptionsBase.java#L152-L162
):

```java
  /**
   * Set the metrics name identifying the reported metrics, useful for grouping metrics
   * with the same name.
   *
   * @param metricsName the metrics name
   * @return a reference to this, so the API can be used fluently
   */
  public ClientOptionsBase setMetricsName(String metricsName) {
    this.metricsName = metricsName;
    return this;
  }
```

**Comment by vietj** [comment]
it seems to actually exist: https://github.com/vert-x3/vertx-dropwizard-metrics/blob/master/src/test/java/io/vertx/ext/dropwizard/MetricsTest.java#L497
