### ISSUE TITLE
metrics maven dependency

### ISSUE THREAD

**Issue by qrman** [vert-x3/vertx-dropwizard-metrics#11]
Hi,
there is a problem with maven dependency for Metrics.

In docs stands:
```xml
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-metrics</artifactId>
  <version>${vertx.metrics.version}</version>
</dependency>
```

I assume that current version should be 3.0.0. But that is not true (latest available for me is 3.0.0-milestone3 version).

However I can find this:

```xml
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-dropwizard-metrics</artifactId>
  <version>3.0.0</version>
</dependency>
```
Which artifact is correct?

**Comment by vietj** [comment]
the later, it should be fixed now I think by @cescoffier today

**Comment by qrman** [comment]
Thanks @vietj

**Comment by cescoffier** [comment]
See https://github.com/vert-x3/issues/issues/14.

It has been fixed for most of the project. Will have a look to the README files.
