### ISSUE TITLE
The HttpClientMetrics `pool-ratio` gauge is wrong

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-dropwizard-metrics#16]
For a single client the computation reports the number of (connection) / (max pool size).

Max pool size is a value per remote server, therefore the computation is wrong and there should be a gauge per server instead.

**Comment by Pahan-Madusha** [comment]
What's the status of this issue?

**Comment by vietj** [comment]
I think actually it was a wrong alarm but it needs to be checked before closing this issue.

**Comment by cescoffier** [comment]
The current code looks good to me.
