### ISSUE TITLE
Methods not used?

### ISSUE THREAD

**Issue by leolux** [vert-x3/vertx-dropwizard-metrics#19]
Where are the methods implemented in https://github.com/vert-x3/vertx-dropwizard-metrics/blob/master/src/main/java/io/vertx/ext/dropwizard/impl/HttpServerMetricsImpl.java used/invoked?

**Comment by vietj** [comment]
by Vert.x Core . this is an SPI implementation.

**Comment by leolux** [comment]
Alright, I got it. Thanks!
