### ISSUE TITLE
Creating multiple HttpClients throws IllegalArgumentException during metrics registration

### ISSUE THREAD

**Issue by mellster2012** [vert-x3/vertx-dropwizard-metrics#20]
When using vertx-dropwizard-metrics 3.2.0 and -Dvertx.metrics.options.enabled=true.
IllegalArgumentException: A metric named vertx.http.clients.connections.max-pool-size already exists

Line 91 in MetricsRegistry in referenced metrics-core 3.1.2

**Comment by mikeppp** [comment]
I was just about to post this as well.

I have a quick repro here if it helps:

https://github.com/mikeppp/vertx-metrix-bug

**Comment by vietj** [comment]
thanks for the repo

**Comment by mikeppp** [comment]
Cheers!

**Comment by rmerinogarcia** [comment]
Is there a way of not aggregating metrics from different httpclients? It could be quite useful in order to not mix statistics from different sources...

**Comment by vietj** [comment]
at the moment no.

it's quite difficult to scope them naturally, how would you do that ?

**Comment by rmerinogarcia** [comment]
Well, why not a reporter per httpclient instance and give the possibility of naming the prefix of the metrics of the reporter (adding a new parameter on the httpclient options):
vertx.http.clients.POOL_GOOGLE_SERVICE.connections.pool-ratio 
vertx.http.clients.POOL_SEARCHER_SERVICE.connections.pool-ratio

**Comment by vietj** [comment]
@rmerinogarcia I like your suggestion

**Comment by vietj** [comment]
so that leaves teh questions of the name of the default client

**Comment by vietj** [comment]
it has to be something like "default"
