### ISSUE TITLE
Document how to use Jolokia and Hawtio

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-dropwizard-metrics#21]

**Comment by krital** [comment]
Has anything been done on this? Do you know if i can find instructions anywhere?

**Comment by cescoffier** [comment]
Here: http://vertx.io/docs/vertx-dropwizard-metrics/java/#_using_jolokia_and_hawtio
and http://vertx.io/docs/vertx-dropwizard-metrics/java/#_using_jolokia_and_jmx4perl_to_expose_metrics_to_nagios

**Comment by dhoffer** [comment]
The part that is missing in the instructions is where to get the Hawtio web app and how to include in the Vertx verticle to serve the web part.
