### ISSUE TITLE
HttpServer metrics for URI with PathParams

### ISSUE THREAD

**Issue by lpouget** [vert-x3/vertx-dropwizard-metrics#42]
Hi,

Is there a way to record in a nice way metrics for URI like : `https://foo.bar/path/:param` (on GET or DELETE for example) ?

Actually, via JMX, I have multiple entries like :
`vertx.http.servers.get-requests./path/1`
`vertx.http.servers.get-requests./path/2`
...

Best regards,

**Comment by vietj** [comment]
Hi,

can you close this issue and ask this question in the user group : https://groups.google.com/forum/?fromgroups#!forum/vertx ?

thanks

**Comment by lpouget** [comment]
Moved to https://groups.google.com/forum/?fromgroups#!topic/vertx/WjuQ_jOlzYo
