### ISSUE TITLE
http client endpoint metric are not under basename vert.x

### ISSUE THREAD

**Issue by updong** [vert-x3/vertx-dropwizard-metrics#43]
I was testing httpclient endpoint metric using version 3.3.2 

```
            vertxOptions.setMetricsOptions(
                    new DropwizardMetricsOptions()
                            .setEnabled(true)
                            .addMonitoredHttpClientEndpoint(new Match().setValue(".*:.*").setType(MatchType.REGEX))
                            .setJmxEnabled(false)
            );
```

and somehow snapshot didn't give me endpoint metrics in following way 

```
            JsonObject metrics = Deployer.metricsService.getMetricsSnapshot(vertx);
```

so I tried using following way and now it returns. 

```
            JsonObject metrics = Deployer.metricsService.getMetricsSnapshot("http");
```

I was expecting them in "vertx.http.clients.endpoint.<host:port>" somehow they are NOT under basename vertx in registry.

**Comment by tsegismont** [comment]
Right, when the http client is not named then the metric base is just
"http.clients", instead of "vertx.http.clients". See https://git.io/v6aNR

Good catch



2016-08-16 0:34 GMT+02:00 updong <notifications@github.com>:
