### ISSUE TITLE
Config from file not working

### ISSUE THREAD

**Issue by kerko** [vert-x3/vertx-dropwizard-metrics#50]
I am trying to use the `vertx.metrics.options.configPath` system property to configure the metrics collection from the commandline. While vertx loads the property correctly the MetricsOptions dont get set with the values like it is specified in the docs.
I am not sure if this is the intended behavior and the documentation is just unclear or this is actually a bug.

**Comment by tsegismont** [comment]
Hi,

Can you show sample code to explain your expectations?

Thanks

2016-10-13 15:32 GMT+02:00 Jan Kerkenhoff <notifications@github.com>:

**Comment by kerko** [comment]
Basically really simple, start your verticle with `-Dvertx.metrics.options.configPath=pathToConfig` . I then expect the config in this file to be read and applied, so that I dont need to configure it in the code. This would be really useful for specifying the monitored eventbushandlers or serverUri. So you don't need to recompile to change what is monitored.

I have the following config file:

```json
{
	"enabled": true,
	"jmxEnabled": true,
	"registryName": "metrics",
	"monitoredEventBusHandlers": [
		{
			"type": "REGEX",
			"value": "de.braintags.io.vertx.paymentservice.PaymentService:.*"
		}
	],
	"monitoredHttpServerUris": [
		{
			"type": "REGEX",
			"value": "\\/payments.*"
		}
	]
}
```

**Comment by tsegismont** [comment]
Have you set the -Dvertx.metrics.options.enabled=true property as well?
Without it the configPath will be ignored.

2016-10-27 14:22 GMT+02:00 Jan Kerkenhoff <notifications@github.com>:

**Comment by kerko** [comment]
Yes I did set that. I already suspected something like this. Apparently the config is pickup fine for the basic parts like `jmxEnabled`. I tested it by setting to false and jmx reporting was disabled as suspected. But the  `monitoredEventBusHandlers` was not applied apparently. When I set it in code it works and with the config file it doesnt. Maybe the syntax is not right ?

**Comment by tsegismont** [comment]
The syntax looks fine. Can you provide a reproducer? Are both `monitoredEventBusHandlers` and `monitoredHttpServerUris` affected?
