### ISSUE TITLE
AbstractMethodError trying to use instanziate TCPMetrics

### ISSUE THREAD

**Issue by inst-dev-1** [vert-x3/vertx-dropwizard-metrics#61]
Hi,
Currently I'm struggling with the following issue using vertx-dropwizard-metrics: 
java.lang.AbstractMethodError: Method io/vertx/ext/dropwizard/impl/VertxMetricsImpl.createMetrics(Lio/vertx/core/net/NetServer;Lio/vertx/core/net/SocketAddress;Lio/vertx/core/net/NetServerOptions;)Lio/vertx/core/spi/metrics/TCPMetrics; is abstract
	at io.vertx.ext.dropwizard.impl.VertxMetricsImpl.createMetrics(VertxMetricsImpl.java)

It seems like the class VertxMetricsImpl has not correctly implement the method. Investigating the related part in the IDE the createMetrics methods is abstract?

Best
Sven

**Comment by tsegismont** [comment]
It sounds like you're using a version of Vert.x Dropwizard Metrics which is
not aligned with Vert.x core.

2017-05-12 9:12 GMT+02:00 inst-dev-1 <notifications@github.com>:

**Comment by inst-dev-1** [comment]
I used the latest one and after switching to 3.3.3 (same as vertx core) it is working like charm.

Thanks
Sven
