### ISSUE TITLE
HttpClient tests failing

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-dropwizard-metrics#66]
Failing since build [2273](https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-dropwizard-metrics/2273/) triggered after merging eclipse/vert.x#2209

**Comment by vietj** [comment]
thanks mate

**Comment by vietj** [comment]
no need to set 3.5.1 milestone as this fixes an issue that was not in 3.5.0
