### ISSUE TITLE
Upgrade to io.dropwizard.metrics version 4.2

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-dropwizard-metrics#68]

**Comment by vietj** [comment]
Cannot be done because Cassandra client depends on version 4.0.x

**Comment by tsegismont** [comment]
@vietj in Vert.x 4, the Cassandra client depends on the Datastax Java Driver 4.9.0 which allows to configure different metrics systems (Dropwizard 4, Micrometer 1.5, Microprofile Metrics).

By default, all Datastax Java Driver metrics are disabled but the Dropwizard module dependency is not optional.

So we could exclude the Dropwizard dependency in the Vert.x Cassandra Client.

Side note: as an exercise, I tried to configure a shared Micrometer registry for Vert.x and the Datastax Java Driver. It worked:

https://gist.github.com/tsegismont/087900c497343bcb154e41d3ec29abb3

**Comment by tsegismont** [comment]
@vietj then they'd have to:

- re-add the dependency on Dropwizard 4
- maintain a Vert.x Metrics SPI implementation with Dropwizard 4

Actually I'm not sure what's the rationale for this issue. Do you remember why you filed it?

If you look at the [Dropwizard dev status table](https://github.com/dropwizard/metrics#metrics), Dropwizard 5 is marked on-pause.
Besides, both Vert.x Dropwizard and DataStax Java Driver depend on Dropwizard 4.0.x.

So it seems to me all is well :-)

**Comment by vietj** [comment]
I think it was filed when Dropwizard 5 was a thing ?

**Comment by vietj** [comment]
shall we try upgrade to release/4.2.x branch ?

**Comment by tsegismont** [comment]
The Dropwizard website promotes the version 4.1. Version 4.2 is still marked as "in-development."

**If** we were to upgrade, version 4.1 sounds like the target to me.

**Comment by tsegismont** [comment]
I asked the Dropwizard team about the 4.2 status. They have a beta3 out already and only a handful of remaining issues and said it should be released soon-_ish_

**Comment by tsegismont** [comment]
Not closed yet. DZ has been upgrade to 4.2 RC2 for 4.1 first beta.
