### ISSUE TITLE
Filter out internal eventbus addresses

### ISSUE THREAD

**Issue by jotak** [vert-x3/vertx-dropwizard-metrics#75]
Once https://github.com/eclipse/vert.x/pull/2516 is merged, internal eventbus addresses will be distinguished with pattern "__vertx.[net|ws|reply].randomUUID".

See https://github.com/vert-x3/vertx-micrometer-metrics/issues/39

**Comment by jotak** [comment]
While looking at the eventbus metrics implementation I noticed that Matchers (with `options.addMonitoredEventBusHandler`) are not used to completely evict metrics related to an address, but only to suppress the `handlers.my_address` counter/timer. I suppose it is the desired behaviour for matchers indeed.

But do we want the same thing for internal addresses (ie: only remove `handlers.__vertx.foo.bar`) or do we also want to ignore them in all other eventbus metrics (ie: they are not counted in the global handler counter, in messages sent/received counts, bytes written etc.)

I suggest that we ignore them totally, as I did in the micrometers similar pr

**Comment by tsegismont** [comment]
@jotak that would be great @jotak . Please go ahead
