### ISSUE TITLE
New EB metric to monitor if a consumer cannot cope with messages delivered

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-dropwizard-metrics#81]
When a message is delivered locally, a handler task is scheduled for execution. If a consumer cannot keep-up with sent messages, the handler tasks will pile up in the executor queue.

Using the EB metrics SPI, it is possible to determine how many messages have been delivered but not yet handled.

Monitoring such a metrics, users could decided how to adapt to high traffic, e.g. spawning new nodes.

**Comment by tsegismont** [comment]
@vietj I took another look at this, it seems "pending" metric really does this job. Perhaps we should simply document/blog about it (got another question today on Gitter).

**Comment by vietj** [comment]
pending is documented already, what do you want to do ?

something like a FAQ ?

**Comment by tsegismont** [comment]
Sorry if my previous comment was unclear.

I originally filed this issue thinking we had no metric to monitor the number of messages scheduled but not handled yet. I took another look today and thought "pending" metric (exists in both Dropwizard and Micrometer implementations) does the job already.

So I have two questions:
1. Can you confirm the pending metric is what we're looking for? I'm not sure why I missed this in the first place so another pair of eyes might be good.
2. How about blogging about the slow consumers problem and how you can use monitoring to determine when you need to deploy new workers?
