### ISSUE TITLE
Http server request metrics incorrectly reported

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-dropwizard-metrics#9]
See failing test suite.

If there is more than one server started at same host+port then each server metrics seems to see total number of requests across all server, not just the requests of that server

**Comment by vietj** [comment]
actually this is expected, the SPI doc says:

```
Note: this method can be called more than one time for the same {@code localAddress} when a server is scaled, it is the responsibility of the metrics implementation to eventually merge metrics.
```

In case of Dropwizard, we aggregate these metrics in the same server.

I've noticed you did this change in Vert.x core : https://github.com/eclipse/vert.x/commit/4c189d5bb48940874cb2bec0add3c74e65831380#commitcomment-11750429 and it seems related, however it was done in a branch and not merged.

In addition this change should:
- change the javadoc to remove the mention about scaling
- also change the metrics SPI creation here too : https://github.com/eclipse/vert.x/blob/4c189d5bb48940874cb2bec0add3c74e65831380/src/main/java/io/vertx/core/http/impl/HttpServerImpl.java#L253

My opinion is that we should rather modify the SPI to provide a discriminant when creating the server (hashCode or a sequence number) so the SPI implementor can distinguish the server but chose to aggregate the metrics.

Keep it mind that when metrics a reported on a cluster in a unified backend (so not local JMX) in a TSDB (time series database, like Hawkular Metrics, InfluxDB, etc...), these servers should be able to aggregate the metrics from the various node of the cluster. Adding this suffix to the host seems rather like an hack that a proper fix.
