### ISSUE TITLE
Server Uris via command line 

### ISSUE THREAD

**Issue by pendula95** [vert-x3/vertx-dropwizard-metrics#91]
We are activating DropWizard Metrics via command line as we are using Launcher class to deploy our Main Verticle which deploys rest of the Verticles. So we pass all confing via command line and I am not suse how we can or if we can pass settings for Http URI metrics. The only example for this is shown via code when creating Vertx object and we don't do this anywhere in code. We are using `metricsService = MetricsService.create(vertx)` to create the merticsService and vertx is passed from AbstractVerticle.

Is it possible to configure this via command line or any other method, if not can it be added as feature?

**Comment by tsegismont** [comment]
Since Vert.x 3.6 you can configure the `VertxOptions` (thus the metrics options too) in an external file. Would that help?

**Comment by pendula95** [comment]
Yes this can work, is there some documentation on VertxOptions via config file?

**Comment by tsegismont** [comment]
@pendula95 see https://vertx.io/blog/eclipse-vert-x-3-6-0-released/#externalized-configuration-of-vert-x-options

```
-options /path/to/vertx/options/file.json
```
