### ISSUE TITLE
Event bus discarded message count

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-dropwizard-metrics#96]
Add a metric to track the number of messages discarded by the event-bus when a consumer cannot handle them. Such message has been received by a consumer and then dropped.

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/issues/3333

**Comment by vietj** [comment]
cc @jotak

**Comment by jotak** [comment]
So, we would add a hook to the SPI, such as: `public void messageDiscardedHandlerMetric handler, boolean local)` , right?
This hook is _also_ going to be called when there's discarded messages due to unregistering handlers, ok?

**Comment by vietj** [comment]
yes @jotak that's what I did in dropwizard : https://github.com/vert-x3/vertx-dropwizard-metrics/commit/e7bef383fd0d7be860ff7e72ebfb88ba3581172b

**Comment by vietj** [comment]
the SPI was added in 3.9 and master

**Comment by jotak** [comment]
Ok, I'm going to do it for micrometer.
BTW: you didn't remove the lines that deal with discarded messages related to unregistration: https://github.com/vert-x3/vertx-dropwizard-metrics/blob/master/src/main/java/io/vertx/ext/dropwizard/impl/EventBusMetricsImpl.java#L280-L282
Is it on purpose? Shouldn't you remove this?

**Comment by vietj** [comment]
it's a mistake, it should be removed since now those lines are accounted by the new SPI callback.

**Comment by vietj** [comment]
@jotak, do you want to have this in 3.9.0 release ?

**Comment by jotak** [comment]
@vietj yes: https://github.com/vert-x3/vertx-micrometer-metrics/pull/103
