### ISSUE TITLE
Discarded messages are still counted as pending

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-dropwizard-metrics#97]
Discarded event bus messages are still counted as pending. When a message is discarded, the pending count should be corrected.

**Comment by vietj** [comment]
cc @jotak

**Comment by jotak** [comment]
@vietj While fixing this on micrometer I had a quick look on dropwizard too and I thought it was already handled, see https://github.com/vert-x3/vertx-dropwizard-metrics/blob/master/src/main/java/io/vertx/ext/dropwizard/impl/EventBusMetricsImpl.java#L280-L282 => pending gauges are reset.

Or, is there some situations where messages are discarded *without* the handler being removed?

For micrometer, I believe https://github.com/vert-x3/vertx-micrometer-metrics/pull/98 did fix it, pending count being reset on unregistration.

**Comment by vietj** [comment]
@jotak yes it happens when a consumer is paused and messages are dropped due to overflow, e.g

```java
MessageConsumer<String> consumer = eventBus.consumer("foo");
consumer.setMaxBufferedMessages(10);
consumer.pause();
consumer.handler(msg -> ...);

for (int i = 0;i < 10;i++) {
  eventBus.send("foo", "msg-" + i);
}
eventBus.send("foo", "msg-11"); // Shall be discarded


```
